---
title: "Proposal for Psychology Department Research Methods 2024-5"
df-print: kable
bibliography: "references.bib"
---

\raggedright

# Research Skills

The Psychology department at Goldsmiths has a number of differentiating
features, upon which it must build in order to ensure it remains
attractive and distinctive.

-   Alchemical, interdisciplinary research programmes and projects
-   Passion for empowering students and producing creative, skillful,
    disruptive agents of change
-   Blend of Art and Science, craft, entrepreneurship, massively
    transferable mind-set/skill-set

Research Methods has to be an adventure, "Alive" with enthusiasm,
inspiring curiosity and intellectual problem-solving.

We have to break the A-Level preconception that Research Methods is dry,
maths-like or indeed difficult.

This must be achieved by: - Practical First - The majority of lab
sessions should be practical and 'hands on'! - Only present
research/methods/topics that are 'ownable' - where we have expertise,
cachet and competitive advantage - and that could NOT be done at
school - 'Relevant & Applicable' above all else. Nothing is taught
'because the BPS says we have to' or that doesn't have widespread use in
a range of future endeavours - Demonstrate and model intellectual
virtue, curiosity, empiricism, skepticism, humility and

Psychology can be a stimulating and joyful endeavour, and learning it is
best achieved in a safe, but challenging environment.

::: callout-important
Psychology is a diverse and highly interdisciplinary field of study that
involves the varied application of systematic methods of inquiry to the
exploration of behavior, mental processes, and social relationships.

As a department we support students in discovering the core knowledge
and skills of the field of psychology, extending a history and tradition
of widening participation, respecting diverse viewpoints and methods and
forging important connections with other disciplines and areas of
practice.

It is our mission to promote intellectual virtue and inspire curiosity,
creativity, critical and analytic thinking in all our students.

Across our exciting portfolio of programmes, we strive to create an
open, supportive, challenging and dynamic learning environment. We share
our passion for psychology through close and active mentorship and
support in labs, lecture halls and beyond.

We believe that the best way to train these virtues is by modelling
them, and so we invest heavily in giving students access to our active
research groups, we encourage and support students in finding a
psychology that is relevant to them and gives them agency to solve
whatever challenges they choose to address.
:::

::: {.callout-warning icon="false"}
At a departmental level we consider the following to be crucial

**1)** Demonstrate understanding and competence regarding the use of
research methodology in psychology from across the range of Qualitative
and Quantitative technique, and use them to collect high quality data.

**2)** Skillfully analyse and correctly interpret data using appropriate
techniques and tools in a Open and Reproducible way.

**3)** Communicate complex ideas and empirical results clearly,
succinctly, and in a range of relevant media and contexts.

**4)** To appreciate the broad and important application of Psychology.

**5)** Demonstrate a clear understanding of key concepts, theoretical
approaches, empirical results, and historical debates in the field of
Psychology.

**6)** Develop meta-learning, meta-cognitive and reflective skills
suitable to support a life of learning.

**7)** Recognize, understand, respect and champion diversity,
inclusivity and stuff.

**8)** Reflect on the ethical imperatives of Psychological practice and
research, and be an agent for good.
:::

------------------------------------------------------------------------

## Weekly structure (all levels)

### 2 hours lecture (+1 hour pre-reading)

We moved to 1 hour (from 2) during the pandemic, and it has severely
limited the amount that can be reasonably covered. In addition to
doubling the lecture time (as is merited by credit weighting alone), we
propose to introduce a weekly expectation that an hour is spent reading
in preparation for the following session.

This could be diverted to other preparatory activities, but the
expectation will be clearly set that a MINIMUM of an hour of preparation
is expected for every lecture.

------------------------------------------------------------------------

### 2 hours lab (+1 hour pre-reading)

Labs are valuable practical sessions and a similar expectation exists
that a student will have completed whatever preparation is expected. Of
course, we understand if things don't always go to plan, so if you can,
please do turn up, but by being prepared, and understanding the activity
being conducted, the learning outcomes are far more achievable.

It will often be the case the the preparation is mostly 'setting the
scene', or giving detailed instructions about what will be happening
that are better delivered in writing, or clarifying what you will be
expected to have done or produced by the end of the lab.

In this module, it is easier to 'keep up than catch up'.

------------------------------------------------------------------------

### 2 hours Interactive Data Skills Tutorials (with short weekly assessment)

Think of this as focussed time students are dedicated to working on
their computers, and so anything that sits within the browser is fair
game here. It's NOT just Stats. Library skills, literature searching,
learning logs and portfolios, as well as collaborative writing or
finding information.

Since the programme will employ an Open Educational Resource Online
Textbook as the central resource for Lectures and Labs, this means that
the notional 4 hours of 'screen time' allocated to this module may often
be closely aligned, but it will also be the case that a wide range of
activity types will be trained and developed, including the Goldsmiths
Library and their extensive online resources, also extensive use of
Posit Cloud will be made, the hub where students will produce technical
reports, blogs and webpages, conduct data analysis and collaborate on
coding and writing exercises.

------------------------------------------------------------------------

Method-neutral and wide Open!

::: {.callout-caution icon="false"}
We embrace an Open Science approach in our efforts to cultivate your
critical evaluation skills, enhance your understanding of the
significance - and power - of research, and equip you with the necessary
graduate-level skills to collect, handle, and interpret data using
programming software for statistical model development, visualisation
and analysis.
:::

### Hours specification (e.g.) Years 1 & 2

| Activity                     | Time | Note      |
|------------------------------|------|-----------|
| Lectures                     | 40   | 2hrs/week |
| Labs                         | 40   | 2hrs/week |
| Data Skills (Online)         | 40   | 2hrs/week |
| Guided Reading/viewing       | 40   | 2hrs/week |
| RPS                          | 20   | 1hr/week  |
| Independent Study/Coursework | 120  | 6hr/week  |

: Notional Hours = 300

## Still thinking about...

### Pre-Arrival / Onboarding

Showcase in Induction week - Staff labs and research projects for the
year.

Year One students self-test

MSc Students - ditto and ability to shop around for supervision

Year 2 develop their pods? Show Y1 and Foundations what they did last
year

Year 3/MSc students - Research Bootcamp and refreshers/skills workshops

Support PhD students and staff
