\-\--
title: Considerations
\-\--

\raggedright

## Questions for discussion

Mini-Dissertation needs to be considered.

Independent projects in Y3 (needs to be considered)

MSc provision? Any changes required/wanted?

## Preparation for 24/5

Need to begin preparation

Lectures x 40

Open Educational Resources Textbook for Research Methods CCBY4.0

Lab Practicals x 40

Open Educational Resources Textbook for Data Skills (e.g. Navarro)
CCBY4.0

Recordings, videos, materials and worksheets for above x 40

Y3/MSc Bootcamp

## Infrastructure

Recording suite

Materials storage

Estates and Facilities

Removal of computer banks in labs to make them more useful for
practicals? e.g. WB218 capacity = 32.

Wall-mounted monitors at least?

## Technology

Posit Cloud as Entry Level although we could make an argument for Ian to
manage a server installation.

Portfolio options? Mahara?

Costs

Chromebooks on loan for labs maybe?

## Risks

Technology obstacles (lower than SPSS)

Finite knowledge within staff

Staff resistance

Staffing and teaching allocation

Recruit next TFs specifically to help build the infrastructure and
programme

## Timetabling

We need timetabling to help us optimise the week

Induction planning

Pre-arrival comms

## 
