---
title: Crap
---

Y1 Term 2 Laydown

+-------------+-------------+-------------+-------------+-------------+
| Sem. 1:     | Research    | \[Sli des\] | [L          | [Read in    |
| Week 1      | Design &    | ( http%20s  | ab](h%20%20 | g](h%20t    |
|             | Data        | : %20//uoe  | %20%%20%202 | %20%20t%20% |
|             |             | % 20psy.gi  | 0t%%20%%202 | 20%20p%20s% |
|             |             | % 20t%20hu  | 02%200tp%2% | 20://%20%%2 |
|             |             | b .io/dap%  | 200s%20%%20 | 020%20%20u% |
|             |             | 2 0%20r1/2  | 20%20://uoe | 2%200o%20%2 |
|             |             | 2 23%20/le  | p%%%2%20020 | 0%20%20ep%2 |
|             |             | c %20tur%2  | %20%2020%20 | %%20200%20% |
|             |             | 0 es/dapR1  | %%2020%20%2 | 20%20sy%20% |
|             |             | % 2%200_le  | %200sy.%20g | 20.githu%20 |
|             |             | c 1_Res%20  | %20%20i%20% | %2%20%200%2 |
|             |             | e a%20rchD  | 20%20t%20h% | 0%2%2%200%2 |
|             |             | e %20sign-  | 20ub.%20%%2 | %200%200%20 |
|             |             | D %20a%20t  | 020%20%20i% | b.i%20%20o% |
|             |             | a .html#1)  | 2%200o%20%2 | %2020%20/da |
|             |             |             | 0%20%20/d%2 | p%2%200r%20 |
|             |             |             | %%20200%20% | %20%20%20%% |
|             |             |             | 20%20ap%20% | 20201/%20%2 |
|             |             |             | 20r1/222%20 | 0%20%%20202 |
|             |             |             | %2%20%200%2 | 2%2023%20/% |
|             |             |             | 0%2%2%200%2 | %202%200%20 |
|             |             |             | %200%200%20 | %20lab%%202 |
|             |             |             | 3/l%20%20a% | 0s/%20%20%% |
|             |             |             | %2020%20bs/ | 2020%20r%20 |
|             |             |             | 1%2%200_%20 | d%%2020%20% |
|             |             |             | %20%20%20%% | 20%20%201%2 |
|             |             |             | 202001%20%2 | 0_%20%20%20 |
|             |             |             | 0%20%%2020_ | %2001.html) |
|             |             |             | d%20es%20i% |             |
|             |             |             | %202%200%20 |             |
|             |             |             | %20gn_%%202 |             |
|             |             |             | 0an%20%20%% |             |
|             |             |             | 2020%20d%20 |             |
|             |             |             | _%%2020%20% |             |
|             |             |             | 20%20%20d%2 |             |
|             |             |             | 0a%20%20%20 |             |
|             |             |             | %20ta.html) |             |
+:============+:============+:============+:============+:============+
| Sem. 1:     | D e         | \[S l ide   | [L          | [Read in    |
| Week 2      | scribing C  | s\]         | ab](h%2     | g](h%20t    |
|             | a t         | (h%%20%20%2 | 0%20t%20%20 | %20%20t%20% |
|             | egorical    | 0%202%200%2 | %20%%20%202 | 20%20p%20s% |
|             | Data        | 0%20%20ttps | 0t%%20%%202 | 20://%20%%2 |
|             |             | %20:%20%20% | 02%200ps%2% | 020%20%20u% |
|             |             | 20//uo%%202 | 200:%20%%20 | 2%200o%20%2 |
|             |             | 0e%20%20%2% | 20%20//uoep | 0%20%20ep%2 |
|             |             | 200p%20s%20 | s%%%2%20020 | %%20200%20% |
|             |             | %2%200y.gi% | %20%2020%20 | 20%20sy%20% |
|             |             | 20%%2%200%2 | %%2020%20%2 | 20.githu%20 |
|             |             | 020thub.%20 | %200y.g%20i | %2%20%200%2 |
|             |             | i%20%20%20% | %20%20t%20% | 0%2%2%200%2 |
|             |             | %2020o%%20% | 20%20h%20u% | %200%200%20 |
|             |             | 202%200/d%2 | 20b.i%20%%2 | b.i%20%20o% |
|             |             | 0a%20%%2020 | 020%20%20o% | %2020%20/da |
|             |             | pr1/222%%%2 | 2%200/%20%2 | p%2%200r%20 |
|             |             | 020%20%2020 | 0%20%20da%2 | %20%20%20%% |
|             |             | %%2020%20%2 | %%20200%20% | 20201/%20%2 |
|             |             | 03/l%20e%20 | 20%20pr%20% | 0%20%%20202 |
|             |             | c%20%20%20t | 201/2223%20 | 2%2023%20/% |
|             |             | u%20res%20% | %2%20%200%2 | %202%200%20 |
|             |             | 20%20%20/%2 | 0%2%2%200%2 | %20lab%%202 |
|             |             | 0d%20%20%20 | %200%200%20 | 0s/%20%20%% |
|             |             | ap%2%%20200 | /la%20%20b% | 2020%20r%20 |
|             |             | %20%20R1%20 | %2020%20s/1 | d%%2020%20% |
|             |             | *lec2*%20%2 | _%2%2000%20 | 20%20%201%2 |
|             |             | %200%20%2%2 | %20%20%20%% | 0_%20%20%20 |
|             |             | 0%2%200%200 | 20202_%20%2 | %2002.html) |
|             |             | Des%20%20c% | 0%20%%2020c |             |
|             |             | 20%20ribi%2 | a%20te%20g% |             |
|             |             | 0n%20%20%20 | %202%200%20 |             |
|             |             | %%2020gC%20 | %20ori%%202 |             |
|             |             | %20%%2020at | 0ca%20%20%% |             |
|             |             | eg%20o%%202 | 2020%20l%20 |             |
|             |             | 0%20%20ric% | _%%2020%20% |             |
|             |             | 20al%20%20% | 20%20%20d%2 |             |
|             |             | 20%20D%20a% | 0a%20%20%20 |             |
|             |             | 20%20%20%20 | %20ta.html) |             |
|             |             | t%20a%20%20 |             |             |
|             |             | %20.html#1) |             |             |
+-------------+-------------+-------------+-------------+-------------+
| Sem. 1:     | D e         | \[Sl ides\] | \[Lab\] ( h | [Read in    |
| Week 3      | scribing C  | (htt%20p    | ttps://u %  | g](h%20t    |
|             | o ntinuous  | %20s%20:    | 2 0oepsy.g  | %20%20t%20% |
|             | Data        | //uo%20%    | i t         | 20%20p%20s% |
|             |             | 20epsy.g    | hu%20b.i o  | 20://%20%%2 |
|             |             | %20%20i%    | / dapr1/%2  | 020%20%20u% |
|             |             | 20th%20u    | 0 2         | 2%200o%20%2 |
|             |             | b.io/da%    | 223/labs /  | 0%20%20ep%2 |
|             |             | %2020%20    | 1 %20_03_n  | %%20200%20% |
|             |             | pr1/%202    | um e        | 20%20sy%20% |
|             |             | 22%203/l    | ric%20\_ d  | 20.githu%20 |
|             |             | %20e%20c    | a ta.html)  | %2%20%200%2 |
|             |             | tu%2%200    |             | 0%2%2%200%2 |
|             |             | res/dapR    |             | %200%200%20 |
|             |             | %20%2%20    |             | b.i%20%20o% |
|             |             | 01_l%20e    |             | %2020%20/da |
|             |             | c3_De%20    |             | p%2%200r%20 |
|             |             | %20sc%20    |             | %20%20%20%% |
|             |             | ribi%20n    |             | 20201/%20%2 |
|             |             | %20gCont    |             | 0%20%%20202 |
|             |             | %20D%20a    |             | 2%2023%20/% |
|             |             | %20t%20a    |             | %202%200%20 |
|             |             | .html#1)    |             | %20lab%%202 |
|             |             |             |             | 0s/%20%20%% |
|             |             |             |             | 2020%20r%20 |
|             |             |             |             | d%%2020%20% |
|             |             |             |             | 20%20%201%2 |
|             |             |             |             | 0_%20%20%20 |
|             |             |             |             | %2003.html) |
+-------------+-------------+-------------+-------------+-------------+
| Sem. 1:     | D e         | \           | \[Lab\] ( h | [Read in    |
| Week 4      | scribing Re | \[ Slides\] | t tps://uo  | g](h%20t    |
|             | l a t       | ( h t       | e p s       | %20%20t%20% |
|             | ionships    | tps://uo e  | y.github .  | 20%20p%20s% |
|             |             | p s         | i o         | 20://%20%%2 |
|             |             | y.github .  | /dapr1/2 22 | 020%20%20u% |
|             |             | i o         | 3 /         | 2%200o%20%2 |
|             |             | /dapr1/2 2  | labs/1\_ 0  | 0%20%20ep%2 |
|             |             | 2 3         | 4 \_        | %%20200%20% |
|             |             | /lecture s  | relation s  | 20%20sy%20% |
|             |             | / d         | h i         | 20.githu%20 |
|             |             | apR1_lec 4  | ps.html)    | %2%20%200%2 |
|             |             | \_ D        |             | 0%2%2%200%2 |
|             |             | escribin g  |             | %200%200%20 |
|             |             | R e         |             | b.i%20%20o% |
|             |             | lationsh i  |             | %2020%20/da |
|             |             | p s         |             | p%2%200r%20 |
|             |             | .html#1)    |             | %20%20%20%% |
|             |             |             |             | 20201/%20%2 |
|             |             |             |             | 0%20%%20202 |
|             |             |             |             | 2%2023%20/% |
|             |             |             |             | %202%200%20 |
|             |             |             |             | %20lab%%202 |
|             |             |             |             | 0s/%20%20%% |
|             |             |             |             | 2020%20r%20 |
|             |             |             |             | d%%2020%20% |
|             |             |             |             | 20%20%201%2 |
|             |             |             |             | 0_%20%20%20 |
|             |             |             |             | %2004.html) |
+-------------+-------------+-------------+-------------+-------------+
| Sem. 1:     | F unctions  | [Slid e     | [L          | [Read in    |
| Week 5      |             | s](h%%2020  | ab](htt%2   | g](h%20t    |
|             |             | %%2%200%2%2 | 0%20p%20%20 | %20%20t%20% |
|             |             | 0020ttps:%2 | %20%%20%202 | 20%20p%20s% |
|             |             | 0%20/%20%20 | 0s%%20%%202 | 20://%20%%2 |
|             |             | %20%%20%202 | 02%200:/%2% | 020%20%20u% |
|             |             | 0/%%20%%202 | 200/%20%%20 | 2%200o%20%2 |
|             |             | 02%200uo%2% | 20%20uoepsy | 0%20%20ep%2 |
|             |             | 200e%20%%20 | .%%%2%20020 | %%20200%20% |
|             |             | 20%20psy.gi | %20%2020%20 | 20%20sy%20% |
|             |             | t%%%2%20020 | %%2020%20%2 | 20.githu%20 |
|             |             | %20%2020%20 | %200git%20h | %2%20%200%2 |
|             |             | %%2020%20%2 | %20%20u%20% | 0%2%2%200%2 |
|             |             | %200hub%20. | 20%20b%20.% | %200%200%20 |
|             |             | %20%20i%20% | 20io/%20%%2 | b.i%20%20o% |
|             |             | 20%20o%20/% | 020%20%20d% | %2020%20/da |
|             |             | 20dap%20%%2 | 2%200a%20%2 | p%2%200r%20 |
|             |             | 020%20%20r% | 0%20%20pr%2 | %20%20%20%% |
|             |             | 2%2001%20%2 | %%20200%20% | 20201/%20%2 |
|             |             | 0%20%20/2%2 | 20%201/%20% | 0%20%%20202 |
|             |             | %%20200%20% | 202223/l%20 | 2%2023%20/% |
|             |             | 20%2022%20% | %2%20%200%2 | %202%200%20 |
|             |             | 203/lect%20 | 0%2%2%200%2 | %20lab%%202 |
|             |             | %2%20%200%2 | %200%200%20 | 0s/%20%20%% |
|             |             | 0%2%2%200%2 | abs%20%20/% | 2020%20r%20 |
|             |             | %200%200%20 | %2020%201_0 | d%%2020%20% |
|             |             | ure%20%20s% | 5%2%200_%20 | 20%20%201%2 |
|             |             | %2020%20/da | %20%20%20%% | 0_%20%20%20 |
|             |             | p%2%200R%20 | 2020fo%20%2 | %2005.html) |
|             |             | %20%20%20%% | 0%20%%2020r |             |
|             |             | 20201_%20%2 | m%20at%20i% |             |
|             |             | 0%20%%2020l | %202%200%20 |             |
|             |             | e%20c5%20_% | %20ve_%%202 |             |
|             |             | %202%200%20 | 0re%20%20%% |             |
|             |             | %20Fun%%202 | 2020%20p%20 |             |
|             |             | 0ct%20%20%% | o%%2020%20% |             |
|             |             | 2020%20i%20 | 20%20%20r%2 |             |
|             |             | o%%2020%20% | 0t%20%20%20 |             |
|             |             | 20%20%20n%2 | %20_a.html) |             |
|             |             | 0s%20%20%20 |             |             |
|             |             | %20.html#1) |             |             |
+-------------+-------------+-------------+-------------+-------------+
| Sem. 1:     | F ormative  |             |             |             |
| Week 6      | feedback    |             |             |             |
|             | week (A)    |             |             |             |
+-------------+-------------+-------------+-------------+-------------+
| Sem. 1:     | P r o       | [Slid e     | \[La b\]    | [Read in    |
| Week 7      | bability    | s           | (h%20%%2020 | g](h%20t    |
|             | Theory      | ](h%%202%20 | ttps://%%%2 | %20%20t%20% |
|             |             | 0t%20%20%2% | 020%20%2020 | 20%20p%20s% |
|             |             | %20200t%20p | %%2020%20%2 | 20://%20%%2 |
|             |             | %20%20%2%20 | 0uoe%20p%20 | 020%20%20u% |
|             |             | 0s://%%2020 | s%20%20%20y | 2%200o%20%2 |
|             |             | %%2%200%2%2 | .%20git%20% | 0%20%20ep%2 |
|             |             | 0020uoeps%2 | 20%20%20h%2 | %%20200%20% |
|             |             | 0%20y%20%20 | 0u%20%20%20 | 20%20sy%20% |
|             |             | %20%%20%202 | b.%2%%20200 | 20.githu%20 |
|             |             | 0.%%20%%202 | %20%20io%20 | %2%20%200%2 |
|             |             | 02%200gi%2% | /dapr1%20%2 | 0%2%2%200%2 |
|             |             | 200t%20%%20 | %200%20%2%2 | %200%200%20 |
|             |             | 20%20hub.io | 0%2%200%200 | b.i%20%20o% |
|             |             | /%%%2%20020 | /22%20%202% | %2020%20/da |
|             |             | %20%2020%20 | 20%203/la%2 | p%2%200r%20 |
|             |             | %%2020%20%2 | 0b%20%20%20 | %20%20%20%% |
|             |             | %200dap%20r | %%2020s/%20 | 20201/%20%2 |
|             |             | %20%201%20% | %           | 0%20%%20202 |
|             |             | 20%20/%202% | 20%%20201\_ | 2%2023%20/% |
|             |             | 20223%20%%2 | 0           | %202%200%20 |
|             |             | 020%20%20/% | 7%20\_%%202 | %20lab%%202 |
|             |             | 2%200l%20%2 | 0%20%20pro% | 0s/%20%20%% |
|             |             | 0%20%20ec%2 | 2           | 2020%20r%20 |
|             |             | %%20200%20% | 0b\_%20%20% | d%%2020%20% |
|             |             | 20%20tu%20% | 20%20t%20h% | 20%20%201%2 |
|             |             | 20res/da%20 | 20%20%20%20 | 0_%20%20%20 |
|             |             | %2%20%200%2 | e%20o%20%20 | %2007.html) |
|             |             | 0%2%2%200%2 | %20ry.html) |             |
|             |             | %200%200%20 |             |             |
|             |             | pR1%20%20_% |             |             |
|             |             | %2020%20lec |             |             |
|             |             | 6%2%200_%20 |             |             |
|             |             | %20%20%20%% |             |             |
|             |             | 2020In%20%2 |             |             |
|             |             | 0%20%%2020t |             |             |
|             |             | r%20oP%20r% |             |             |
|             |             | %202%200%20 |             |             |
|             |             | %20oba%%202 |             |             |
|             |             | 0bi%20%20%% |             |             |
|             |             | 2020%20l%20 |             |             |
|             |             | i%%2020%20% |             |             |
|             |             | 20%20%20t%2 |             |             |
|             |             | 0y%20%20%20 |             |             |
|             |             | %20.html#1) |             |             |
+-------------+-------------+-------------+-------------+-------------+
| Sem. 1:     | P r o       | [Slid e     | \[L a b\] ( | [Read in    |
| Week 8      | bability    | s           | https:/% 2  | g](h%20t    |
|             | Rules       | ](h%%202%20 | 0%20/uoe p  | %20%20t%20% |
|             |             | 0t%20%20%2% | sy%20.gi t  | 20%20p%20s% |
|             |             | %20200t%20p | %20hub%2 0  | 20://%20%%2 |
|             |             | %20%20%2%20 | .io/dapr %  | 020%20%20u% |
|             |             | 0s://%%2020 | 2%2001/2 2  | 2%200o%20%2 |
|             |             | %%2%200%2%2 | 23/la%20 b  | 0%20%20ep%2 |
|             |             | 0020uoeps%2 | s%20/1_0 8  | %%20200%20% |
|             |             | 0%20y%20%20 | %20_prob \_ | 20%20sy%20% |
|             |             | %20%%20%202 | %20r%20u l  | 20.githu%20 |
|             |             | 0.%%20%%202 | es.html)    | %2%20%200%2 |
|             |             | 02%200gi%2% |             | 0%2%2%200%2 |
|             |             | 200t%20%%20 |             | %200%200%20 |
|             |             | 20%20hub.io |             | b.i%20%20o% |
|             |             | /%%%2%20020 |             | %2020%20/da |
|             |             | %20%2020%20 |             | p%2%200r%20 |
|             |             | %%2020%20%2 |             | %20%20%20%% |
|             |             | %200dap%20r |             | 20201/%20%2 |
|             |             | %20%201%20% |             | 0%20%%20202 |
|             |             | 20%20/%202% |             | 2%2023%20/% |
|             |             | 20223%20%%2 |             | %202%200%20 |
|             |             | 020%20%20/% |             | %20lab%%202 |
|             |             | 2%200l%20%2 |             | 0s/%20%20%% |
|             |             | 0%20%20ec%2 |             | 2020%20r%20 |
|             |             | %%20200%20% |             | d%%2020%20% |
|             |             | 20%20tu%20% |             | 20%20%201%2 |
|             |             | 20res/da%20 |             | 0_%20%20%20 |
|             |             | %2%20%200%2 |             | %2008.html) |
|             |             | 0%2%2%200%2 |             |             |
|             |             | %200%200%20 |             |             |
|             |             | pR1%20%20_% |             |             |
|             |             | %2020%20lec |             |             |
|             |             | 7%2%200_%20 |             |             |
|             |             | %20%20%20%% |             |             |
|             |             | 2020Pr%20%2 |             |             |
|             |             | 0%20%%2020o |             |             |
|             |             | b%20ab%20i% |             |             |
|             |             | %202%200%20 |             |             |
|             |             | %20lit%%202 |             |             |
|             |             | 0yR%20%20%% |             |             |
|             |             | 2020%20u%20 |             |             |
|             |             | l%%2020%20% |             |             |
|             |             | 20%20%20e%2 |             |             |
|             |             | 0s%20%20%20 |             |             |
|             |             | %20.html#1) |             |             |
+-------------+-------------+-------------+-------------+-------------+
| Sem. 1:     | Random V    | \           | \[Lab\] ( h | [Read in    |
| Week 9      | ariables (  | \[ Slides\] | t tps://uo  | g](h%20t    |
|             | D iscrete)  | ( h t       | e p s       | %20%20t%20% |
|             |             | tps://uo e  | y.github .  | 20%20p%20s% |
|             |             | p s         | i o         | 20://%20%%2 |
|             |             | y.github .  | /dapr1/2 22 | 020%20%20u% |
|             |             | i o         | 3 /         | 2%200o%20%2 |
|             |             | /dapr1/2 2  | labs/1\_ 0  | 0%20%20ep%2 |
|             |             | 2 3         | 9 \_        | %%20200%20% |
|             |             | /lecture s  | discrete \_ | 20%20sy%20% |
|             |             | / d         | d i         | 20.githu%20 |
|             |             | apR1_lec 8  | st.html)    | %2%20%200%2 |
|             |             | \_ D        |             | 0%2%2%200%2 |
|             |             | iscreteP r  |             | %200%200%20 |
|             |             | o b         |             | b.i%20%20o% |
|             |             | abilityD i  |             | %2020%20/da |
|             |             | s t         |             | p%2%200r%20 |
|             |             | .html#1)    |             | %20%20%20%% |
|             |             |             |             | 20201/%20%2 |
|             |             |             |             | 0%20%%20202 |
|             |             |             |             | 2%2023%20/% |
|             |             |             |             | %202%200%20 |
|             |             |             |             | %20lab%%202 |
|             |             |             |             | 0s/%20%20%% |
|             |             |             |             | 2020%20r%20 |
|             |             |             |             | d%%2020%20% |
|             |             |             |             | 20%20%201%2 |
|             |             |             |             | 0_%20%20%20 |
|             |             |             |             | %2009.html) |
+-------------+-------------+-------------+-------------+-------------+
| Sem. 1:     | Random V    | \[S l ide   | \[L ab\]    | [Read in    |
| Week 10     | ariables (  | s\]         | (https:%    | g](h%20t    |
|             | C o n       | (h%%20%20%2 | %2020%20    | %20%20t%20% |
|             | tinuous)    | 0%202%200%2 | //uo%20e    | 20%20p%20s% |
|             |             | 0%20%20ttps | ps%20y.g    | 20://%20%%2 |
|             |             | %20:%20%20% | %20i%20t    | 020%20%20u% |
|             |             | 20//uo%%202 | hu%2%200    | 2%200o%20%2 |
|             |             | 0e%20%20%2% | b.io/dap    | 0%20%20ep%2 |
|             |             | 200p%20s%20 | %20%2%20    | %%20200%20% |
|             |             | %2%200y.gi% | 0r1/%202    | 20%20sy%20% |
|             |             | 20%%2%200%2 | 223/l%20    | 20.githu%20 |
|             |             | 020thub.%20 | %20ab%20    | %2%20%200%2 |
|             |             | i%20%20%20% | s/1\_%201   | 0%2%2%200%2 |
|             |             | %2020o%%20% | %200_con    | %200%200%20 |
|             |             | 202%200/d%2 | %20t%20\_   | b.i%20%20o% |
|             |             | 0a%20%%2020 | %20d%20i    | %2020%20/da |
|             |             | pr1/222%%%2 | st.html)    | p%2%200r%20 |
|             |             | 020%20%2020 |             | %20%20%20%% |
|             |             | %%2020%20%2 |             | 20201/%20%2 |
|             |             | 03/l%20e%20 |             | 0%20%%20202 |
|             |             | c%20%20%20t |             | 2%2023%20/% |
|             |             | u%20res%20% |             | %202%200%20 |
|             |             | 20%20%20/%2 |             | %20lab%%202 |
|             |             | 0d%20%20%20 |             | 0s/%20%20%% |
|             |             | ap%2%%20200 |             | 2020%20r%20 |
|             |             | %20%20R1%20 |             | d%%2020%20% |
|             |             | *lec9*%20%2 |             | 20%20%201%2 |
|             |             | %200%20%2%2 |             | 0_%20%20%20 |
|             |             | 0%2%200%200 |             | %2010.html) |
|             |             | Con%20%20t% |             |             |
|             |             | 20%20inuo%2 |             |             |
|             |             | 0u%20%20%20 |             |             |
|             |             | %%2020sP%20 |             |             |
|             |             | %20%%2020ro |             |             |
|             |             | ba%20b%%202 |             |             |
|             |             | 0%20%20ili% |             |             |
|             |             | 20ty%20%20% |             |             |
|             |             | 20%20D%20i% |             |             |
|             |             | 20%20%20%20 |             |             |
|             |             | s%20t%20%20 |             |             |
|             |             | %20.html#1) |             |             |
+-------------+-------------+-------------+-------------+-------------+
| Sem. 1:     | Sampling    | [Slide      | [La         | [Read in    |
| Week 11     |             | s]          | b](http     | g](h%20t    |
|             |             | (h%20%20t%2 | s%%%2%20020 | %20%20t%20% |
|             |             | 0%20%%2020t | %20%2020%20 | 20%20p%20s% |
|             |             | ps:%%202%20 | %%2020%20%2 | 20://%20%%2 |
|             |             | 0/%20%20%2% | %200://%20u | 020%20%20u% |
|             |             | %20200/%20u | %20%20o%20% | 2%200o%20%2 |
|             |             | %20%20%2%20 | 20%20e%20p% | 0%20%20ep%2 |
|             |             | 0oeps%%2020 | 20sy.%20%%2 | %%20200%20% |
|             |             | %%2%200%2%2 | 020%20%20g% | 20%20sy%20% |
|             |             | 0020y.git%2 | 2%200i%20%2 | 20.githu%20 |
|             |             | 0%20h%20%20 | 0%20%20th%2 | %2%20%200%2 |
|             |             | %20%%20%202 | %%20200%20% | 0%2%2%200%2 |
|             |             | 0u%%20%%202 | 20%20ub%20% | %200%200%20 |
|             |             | 02%200b.%2% | 20.io/da%20 | b.i%20%20o% |
|             |             | 200i%20%%20 | %2%20%200%2 | %2020%20/da |
|             |             | 20%20o/dapr | 0%2%2%200%2 | p%2%200r%20 |
|             |             | 1%%%2%20020 | %200%200%20 | %20%20%20%% |
|             |             | %20%2020%20 | pr1%20%20/% | 20201/%20%2 |
|             |             | %%2020%20%2 | %2020%20222 | 0%20%%20202 |
|             |             | %200/22%202 | 3%2%200/%20 | 2%2023%20/% |
|             |             | %20%203%20% | %20%20%20%% | %202%200%20 |
|             |             | 20%20/%20l% | 2020la%20%2 | %20lab%%202 |
|             |             | 20ect%20%%2 | 0%20%%2020b | 0s/%20%20%% |
|             |             | 020%20%20u% | s%20/1%20_% | 2020%20r%20 |
|             |             | 2%200r%20%2 | %202%200%20 | d%%2020%20% |
|             |             | 0%20%20es%2 | %2011_%%202 | 20%20%201%2 |
|             |             | %%20200%20% | 0sa%20%20%% | 0_%20%20%20 |
|             |             | 20%20/d%20% | 2020%20m%20 | %2011.html) |
|             |             | 20apR1_l%20 | p%%2020%20% |             |
|             |             | %2%20%200%2 | 20%20%20l%2 |             |
|             |             | 0%2%2%200%2 | 0i%20%20%20 |             |
|             |             | %200%200%20 | %20ng.html) |             |
|             |             | ec1%20%200% |             |             |
|             |             | %2020%20_Sa |             |             |
|             |             | m%2%200p%20 |             |             |
|             |             | %20%20%20%% |             |             |
|             |             | 2020le%20%2 |             |             |
|             |             | 0%20%%2020s |             |             |
|             |             | -%20Sa%20m% |             |             |
|             |             | %202%200%20 |             |             |
|             |             | %20pli%%202 |             |             |
|             |             | 0ng%20%20%% |             |             |
|             |             | 2020%20D%20 |             |             |
|             |             | i%%2020%20% |             |             |
|             |             | 20%20%20s%2 |             |             |
|             |             | 0t%20%20%20 |             |             |
|             |             | %20.html#1) |             |             |
+-------------+-------------+-------------+-------------+-------------+

| Sem. 2: Week 1 | Confidence intervals                                   | [Sli des](ht%20tps://%20%2%200uoepsy.%20%20github%20.%%2020io/dapr1/%202%2022%203/%20lec%20tures%20/da%2%200pr%201_2_01_%20c%20onf%20int%2%200_2223.pdf) | \[Lab\] (https://u oepsy.gith ub.io/dapr 1/2223/lab s/2_01_con fint.html)                                                                     | [Re ading](htt%20ps%%2020://uoeps%%202%200y.gith%20ub.%20i%20o%20/dapr%201/2%202%2023/%20l%20abs/rd%20%2%2002_01.html) |
|:---------------|:-------------------------------------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------|:----------------------------------------------------------------------------------------------------------------------------------------------|:-----------------------------------------------------------------------------------------------------------------------|
| Sem. 2: Week 2 | Hypothesis testing: p-values                           | [S lid es](https:%20%2%200//uoeps%20%20y.gith%20u%%2020b.io/dapr%201%20/2%2022%203/l%20ectur%20es/%2%200da%20pr1_2_0%202%20_ht%20_pv%2%200alues.pdf)     | [Lab](ht%20%20tps:/%20%20/uoep%20sy%%2020.github.%%202%200io/dap%20r1/%202%202%2023/la%20bs/%202%20_02%20_%20ht_pva%20%2%200lues.html)        | [Re ading](htt%20ps%%2020://uoeps%%202%200y.gith%20ub.%20i%20o%20/dapr%201/2%202%2023/%20l%20abs/rd%20%2%2002_02.html) |
| Sem. 2: Week 3 | Hypothesis testing: critical values                    | \[Slid es\] (https://u %20oepsy.g ithub.%20i o/dapr1/22 23%20/lect ures/dap%2 0r1_2\_03_h t_cr%20itv alues.pdf)                                          | [La b](htt%20ps%20%20://uo%20%20epsy.%20gi%%2020thub.io/%%202%200dapr1/%20222%203%20/%20labs/%202_0%203%20_ht%20_%20critva%20%2%200lues.html) | [Re ading](htt%20ps%%2020://uoeps%%202%200y.gith%20ub.%20i%20o%20/dapr%201/2%202%2023/%20l%20abs/rd%20%2%2002_03.html) |
| Sem. 2: Week 4 | Connecting Hypothesis testing and confidence intervals | \[Slide s\] (https:/%20 /uoeps%20y% 20.github.i o%20/d%20ap r1/%202223/ lec%2%200tu res/dap%20r 1_2%20_04%2 0_htci.pdf)                                  | [L ab](h%20%20ttps:%20//%%2020uoepsy.g%%202%200ithub.%20io/%20d%20a%20pr1/2%20223%20/%20lab%20s%20/2_04_%20%2%200htci.html)                   | [Re ading](htt%20ps%%2020://uoeps%%202%200y.gith%20ub.%20i%20o%20/dapr%201/2%202%2023/%20l%20abs/rd%20%2%2002_04.html) |
| Sem. 2: Week 5 | Errors, Power, Effect size, and A ssumptions           | [Sl ide s](h%20ttps:/%20%2%200/uoepsy%20%20.githu%20b%%2020.io/dapr1%20/%2022%2023%20/le%20cture%20s/d%2%200ap%20r1_2_05%20_%20err%20ors%2%200power.pdf) | [La b](htt%20ps%20%20://uo%20%20epsy.%20gi%%2020thub.io/%%202%200dapr1/%20222%203%20/%20labs/%202_0%205%20_ht%20e%20rrorsp%20%2%200ower.html) | [Re ading](htt%20ps%%2020://uoeps%%202%200y.gith%20ub.%20i%20o%20/dapr%201/2%202%2023/%20l%20abs/rd%20%2%2002_05.html) |

| 0   | [Course I ntro](https:/%20/uo%20e%20psy.%20g%20ithub.io/%20%20dap%20r1/2122%20/lect%2%200ures%20/dapR%201_%20l%%2020ec0_CourseIntro.html)                                                | [Intro to R & RStu dio](ht%20tps%20:%20//uo%20e%20psy.githu%20%20b.i%20o/dapr1%20/2122%2%200/lab%20s/int%20ro%20_%%2020r_rstudio_year1.html)                |
|-----|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1   | [Research Design & Data](htt%20ps%20://%20uoepsy.%20git%20h%20ub.i%20o%20/dapr1/21%20%2022/%20lecture%20s/dap%2%200R1_l%20ec1_R%20es%20e%%2020archDesign-Data.html)                      | \[Data Typ es\] (http%20s%20://uoepsy .gi%20thub.io%20/dapr 1/21%2022/la%20bs%20/ 1_01_data_types.html)                                                     |
| 2   | [Describing Categorical Dat a](https://u%20oe%20psy%20.github%20.io%20/%20dapr%201%20/2122/lec%20%20tur%20es/dapR%201_lec%2%2002_De%20scrib%20in%20g%%2020CategoricalData.html)          | [Categorical Dat a](h%20ttps%20:%20//uoepsy.%20%20git%20hub.io/%20dapr1%2%200/212%202/lab%20s/%201%%2020_02_categorical.html)                               |
| 3   | [Describing Continuous Data](ht%20tp%20s:/%20/uoepsy%20.gi%20t%20hub.%20i%20o/dapr1/2%20%20122%20/lectur%20es/da%2%200pR1_%20lec3_%20De%20s%%2020cribingContData.html)                   | \[Numerical D ata\] (htt%20p%20s://uoeps%20 y.g%20ithub.i%20o/dap%2 0r1/2%20122/l%20ab%20s% 20/1_03_numerical.html)                                         |
| 4   | [Describing Relationsh ips](https:/%20/u%20oep%20sy.gith%20ub.%20i%20o/da%20p%20r1/2122/l%20%20ect%20ures/da%20pR1_l%2%200ec4_%20Descr%20ib%20i%%2020ngRelationships.html)               | \[Relationships\] (h t tps:/%20/uoepsy.githu b. i o/dapr1/2122/%20labs/ 1\_ 0 4_relationships.html)                                                         |
| 5   | [F un ctions](https%20://%20u%20oeps%20y%20.github.i%20%20o/d%20apr1/21%2022/le%2%200ctur%20es/da%20pR%201%%2020_lec5_Functions.html)                                                    | \[Functi ons\] (htt%20p%20s://uoeps%20 y.g%20ithub.i%20o/dap%2 0r1/2%20122/l%20ab%20s% 20/1_05_functions.html)                                              |
| 6   | -- Break Week --                                                                                                                                                                         | --                                                                                                                                                          |
| 7   | [Intro to Prob ability](ht%20tps%20://uoep%20sy.%20g%20ithu%20b%20.io/dapr1%20%20/21%2022/lect%20ures/%2%200dapR%201_lec%206_%20I%%2020ntroProbability.html)                             | [Probability Basic s](http%20s:/%20/%20uoep%20s%20y.github.%20%20io/%20dapr1/2%20122/l%2%200abs/%201_07_%20pr%20o%%2020bability_basics.html)                |
| 8   | [Probability Rules](ht%20tps%20://uoep%20sy.%20g%20ithu%20b%20.io/dapr1%20%20/21%2022/lect%20ures/%2%200dapR%201_lec%207_%20P%%2020robabilityRules.html)                                 | [Probability Rul es](htt%20ps:%20/%20/uoe%20p%20sy.github%20%20.io%20/dapr1/%202122/%2%200labs%20/1_08%20_p%20r%%2020obability_rules.html)                  |
| 9   | [Discrete Probability Distributi ons](https:/%20/u%20oep%20sy.gith%20ub.%20i%20o/da%20p%20r1/2122/l%20%20ect%20ures/da%20pR1_l%2%200ec8_%20Discr%20et%20e%%2020ProbabilityDist.html)     | [Discrete Di stributio ns](h%20ttps://%20uoe%20p%20sy.g%20i%20thub.io/d%20%20apr%201/2122/%20labs/%2%2001_09%20_disc%20re%20t%%2020e_distributions.html)    |
| 10  | [Continuous Probability Distribution s](https://u%20oe%20psy%20.github%20.io%20/%20dapr%201%20/2122/lec%20%20tur%20es/dapR%201_lec%2%2009_Co%20ntinu%20ou%20s%%2020ProbabilityDist.html) | [Continuous Dist ributions](htt%20ps://uo%20eps%20y%20.git%20h%20ub.io/dap%20%20r1/%202122/la%20bs/1_%2%20010_c%20ontin%20uo%20u%%2020s_distributions.html) |
| 11  | [Samples and Sampling Distributio ns](https%20:/%20/uo%20epsy.gi%20thu%20b%20.io/%20d%20apr1/2122%20%20/le%20ctures/%20dapR1%2%200_lec%2010_Sa%20mp%20l%%2020es-SamplingDist.html)       | [Sampling Di stributio ns](h%20ttps://%20uoe%20p%20sy.g%20i%20thub.io/d%20%20apr%201/2122/%20labs/%2%2001_11%20_samp%20li%20n%%2020g_distributions.html)    |

#### **Semester 2**

| **Week** | **Lecture**                                                                                                                                              | **Workbook**                                                                                                                                      |
|:---------|:---------------------------------------------------------------------------------------------------------------------------------------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------|
| 1        | [Confidence Interv a ls](ht%20tps://uoepsy%20%20%20.github.i%20o/dapr1%2%200/2122/lectu%20res%20/d%%2020apr1_2_01_confint.pdf)                           | [Confidence Interval s](https:/%20/%20uoep%20sy.github.%2%20%200io/dapr1/%202122/la%2%200bs/2_01_c%20onf%20id%%2020ence_intervals.html)           |
| 2        | \[Hypothesis Testing: P-Values\] (https%20://uoepsy.gi%20 %20thub.io/d%20apr1/21%2 022/lectures%20/da%20pr% 201_2\_02_ht_pvalues.pdf)                    | [Hypothesis Testing: P-Value s](ht%20tps://uoep%2%20%200sy.github%20.io/dap%2%200r1/2122/l%20abs%20/2%%2020_02_ht_pvalues.html)                   |
| 3        | [Hypothesis Testing: Critical V alues](h%20t%20tps://%20uoepsy.githu%20%20%20b.io/dapr%201/2122/%2%200lectures/da%20pr1%20_2%%2020_03_ht_critvalues.pdf) | [Hypothesis Testing: Critical Values](h%20ttps%20://uoepsy.%2%20%200github.io%20/dapr1/%2%2002122/labs%20/2_%2003%%2020_ht_critvalues.html)       |
| 4        | \[Hypothesis Testing & Confidence Intervals\] (h ttps://uoe%20psy.githu b. io/dapr1/2122/le%20ctu res /dapr1_2\_04_htci.pdf)                             | [Hypothesis Testing & Confidence Interva ls](https:%2%20%200//uoepsy.%20github.%2%200io/dapr1/%20212%202/%%2020labs/2_04_htci.html)               |
| 5        | \[Errors, Power, Effect Size & Assu mptions\] (https:%20//uoepsy.git %20hub.io/da%20pr1/212 2/lectures/%20dap%20r1 \_2_05_errorspower.pdf)               | [Errors, Power, Effect Size & Ass umptions](h%20ttps%20://uoepsy.%2%20%200github.io%20/dapr1/%2%2002122/labs%20/2_%2005%%2020_hterrorspower.html) |
| 6        | -- Break Week --                                                                                                                                         | --                                                                                                                                                |
| 7        | \[One Sample T-test\] (https:%20//uoepsy.git %20hub.io/da%20pr1/212 2/lectures/%20dap%20r1 \_lec16_onesamplet.pdf)                                       | [One Sample T-tes t](ht%20tps://uoep%2%20%200sy.github%20.io/dap%2%200r1/2122/l%20abs%20/2%%2020_07_onesamplet.html)                              |
| 8        | [Independent Samples T -test](h%20t%20tps://%20uoepsy.githu%20%20%20b.io/dapr%201/2122/%2%200lectures/da%20pr1%20_l%%2020ec17_independentt.pdf)          | \[Independent T-test\] (http%20s://uoepsy%2 0.github.i%20o/dapr1 /2122/lab%20s/2%20_0 8_independentt.html)                                        |
| 9        | [Paired Samples T-te s t](htt%20ps://uoepsy.%20%20%20github.io%20/dapr1/%2%2002122/lectur%20es/%20da%%2020pr1_lec18_pairedt.pdf)                         | \[Paired T-test\] (h ttps://u%20oepsy.git hu b.io/dapr1/212%202/l ab s/2_09_pairedt.html)                                                         |
| 10       | \[Chi-Square Tests\] (https%20://uoepsy.gi%20 %20thub.io/d%20apr1/21%2 022/lectures%20/da%20pr% 201_lec19_Chisquare.pdf)                                 | [Chi-Square Tes t s](h%20ttps://uoe%2%20%200psy.githu%20b.io/da%2%200pr1/2122/%20lab%20s/%%20202_10_chisquare.html)                               |
| 11       | [Correla tions](h%20t%20tps://%20uoepsy.githu%20%20%20b.io/dapr%201/2122/%2%200lectures/da%20pr1%20_l%%2020ec20_Correlations.pdf)                        | [Covariance & Correl ation](htt%2%20%200ps://uoep%20sy.gith%2%200ub.io/dap%20r1/%2021%%202022/2_11_covcor.html)                                   |

\newpage

#### **Semester 1**

+----------+----------------------------+----------------------------+
| **Week** | **Lecture**                | **Workbook**               |
+:=========+:===========================+:===========================+
| 1        | \[Preli minaries\] (       | \[Functions & Mod els\]    |
|          | https%20://uoepsy.g% 2     | (https:%%2020//uoeps       |
|          | 0ithub.io/%20dapr2/2 1     | y.%20github.%20io/da       |
|          | 22/lectur%20es/%20da p     | pr2/2%20122%20/l%20a       |
|          | r2_01_Prelims.html)\       | bs/1_01_models.html)       |
|          | \[Functions & M od els\]   |                            |
|          | (https:%20//uo%20%20e%20ps |                            |
|          | y.gi%%2020thub.io%20%20%20 |                            |
|          | /d%20apr2/21%2022/le%20%2% |                            |
|          | 200cture%20s/d%20ap%20r%20 |                            |
|          | %%20202_02_functions.html) |                            |
+----------+----------------------------+----------------------------+
| 2        | \[Linear Model Intro\] (   | \[Simple Linear Regr essi  |
|          | https%20://uoepsy.g% 2     | o n\]                      |
|          | 0ithub.io/%20dapr2/2 1     | (htt%%2020ps://uo%20%20%20 |
|          | 22/lectur%20es/%20da p     | ep%20sy.gith%20ub.io%20%2% |
|          | r2_03_LMintro.html)\       | 200/dapr%202/2%2012%202%20 |
|          | [Linear Model Coe ff ic    | %%2020/labs/1_02_slr.html) |
|          | ient                       |                            |
|          | s](http%20s:               |                            |
|          | //%20%20u%20oe%20psy.%%202 |                            |
|          | 0github.%20%20%20%20io%20/ |                            |
|          | dapr2/%202122/%20%2%%20200 |                            |
|          | lectu%20res%20/d%20a%20%20 |                            |
|          | %%2020pr2_04_LMcoefs.html) |                            |
+----------+----------------------------+----------------------------+
| 3        | \[Model Evalua tion\]      | [Model F                   |
|          | (htt%20ps://u%20oeps       | it](ht%20tp                |
|          | y.githu%%2020b.io/da       | s:%20%20/%20/u%20oeps%%202 |
|          | pr%202/2122/%20lectu       | 0y.githu%20%20%20%20b.%20i |
|          | res/d%20apr%202\_%200      | o/dapr%202/212%20%2%%20200 |
|          | 5_LMmodeleval.html)\       | 2/lab%20s/1%20_0%203%20%20 |
|          | [Standardized Coefficient  | %%2020_slr_model_fit.html) |
|          | s](ht%20%                  |                            |
|          | 20tp%20s:%2%200//uoep%20sy |                            |
|          | .g%20%20i%20th%20ub.i%%202 |                            |
|          | 0o/dapr2%20%20%20%20/2%201 |                            |
|          | 22/lec%20tures%20%2%%20200 |                            |
|          | /dapr%202_0%206_%20L%20%20 |                            |
|          | %%2020Mstandardized.html)\ |                            |
|          | \[Binary Pr edictors\] (   |                            |
|          | https%20://uoepsy.g% 2     |                            |
|          | 0ithub.io/%20dapr2/2 1     |                            |
|          | 22/lectur%20es/%20da p     |                            |
|          | r2_07_LMBinary.html)       |                            |
+----------+----------------------------+----------------------------+
| 4        | \[Multiple Predic tors\]   | \[Multiple Linear Regr     |
|          | (htt%20ps://u%20oeps       | essi o n\]                 |
|          | y.githu%%2020b.io/da       | (htt%%2020ps://uo%20%20%20 |
|          | pr%202/2122/%20lectu       | ep%20sy.gith%20ub.io%20%2% |
|          | res/d%20apr%202\_%200      | 200/dapr%202/2%2012%202%20 |
|          | 8_LM_multiple.html)\       | %%2020/labs/1_04_mlr.html) |
|          | [Categorical Predictors    |                            |
|          | with \>2 Leve              |                            |
|          | ls](h%20%                  |                            |
|          | 20tt%20ps%2%200://uoe%20ps |                            |
|          | y.%20%20g%20it%20hub.%%202 |                            |
|          | 0io/dapr%20%20%20%202/%202 |                            |
|          | 122/le%20cture%20%2%%20200 |                            |
|          | s/dap%20r2_%2009%20_%20%20 |                            |
|          | %%2020LM_categorical.html) |                            |
+----------+----------------------------+----------------------------+
| 5        | [Interactions (Continuous  | \[Interactions I\]         |
|          | \* Categoric al            | (https:%%2020//uoeps       |
|          | )                          | y.%20github.%20io/da       |
|          | ](ht%20tp%2%200s://uo%20ep | pr2/2%20122%20/l%20a       |
|          | sy%20%20.%20gi%20thub%%202 | bs/1_05_int_nc.html)       |
|          | 0.io/dap%20%20%20%20r2%20/ |                            |
|          | 2122/l%20ectur%20%2%%20200 |                            |
|          | es/da%20pr2%20_1%200%20%20 |                            |
|          | %%2020_interactions1.html) |                            |
+----------+----------------------------+----------------------------+
| 6        | -- Break Week --           | --                         |
+----------+----------------------------+----------------------------+
| 7        | [Interactions (Continuous  | \[Interactions II\]        |
|          | \* Continuo us             | (https:%%2020//uoeps       |
|          | )                          | y.%20github.%20io/da       |
|          | ](ht%20tp%2%200s://uo%20ep | pr2/2%20122%20/l%20a       |
|          | sy%20%20.%20gi%20thub%%202 | bs/1_07_int_nn.html)       |
|          | 0.io/dap%20%20%20%20r2%20/ |                            |
|          | 2122/l%20ectur%20%2%%20200 |                            |
|          | es/da%20pr2%20_1%200%20%20 |                            |
|          | %%2020_interactions2.html) |                            |
+----------+----------------------------+----------------------------+
| 8        | [Interactions (Categorical | \[Interactions III\]       |
|          | \* Categoric al            | (https:%%2020//uoeps       |
|          | )                          | y.%20github.%20io/da       |
|          | ](ht%20tp%2%200s://uo%20ep | pr2/2%20122%20/l%20a       |
|          | sy%20%20.%20gi%20thub%%202 | bs/1_08_int_cc.html)       |
|          | 0.io/dap%20%20%20%20r2%20/ |                            |
|          | 2122/l%20ectur%20%2%%20200 |                            |
|          | es/da%20pr2%20_1%201%20%20 |                            |
|          | %%2020_interactions3.html) |                            |
+----------+----------------------------+----------------------------+
| 9        | \[Assumpt ions\]           | [Assumptions & Diag        |
|          | (htt%20ps://u%20oeps       | nostics](ht                |
|          | y.githu%%2020b.io/da       | tp%20%20s%20:/%20/uoe%%202 |
|          | pr%202/2122/%20lectu       | 0psy.git%20%20%20%20hu%20b |
|          | res/d%20apr%202\_%201      | .io/da%20pr2/2%20%2%%20200 |
|          | 2_assumptions.html)\       | 122/l%20abs%20/1%20_%20%20 |
|          | [Diagnostics               | %%202009_assumptions.html) |
|          | I                          |                            |
|          | ](ht%20tp%2%200s://uo%20ep |                            |
|          | sy%20%20.%20gi%20thub%%202 |                            |
|          | 0.io/dap%20%20%20%20r2%20/ |                            |
|          | 2122/l%20ectur%20%2%%20200 |                            |
|          | es/da%20pr2%20_1%203%20%20 |                            |
|          | %%2020_diagnostics1.html)\ |                            |
|          | \[Diagnostics II\]         |                            |
|          | (htt%20ps://u%20oeps       |                            |
|          | y.githu%%2020b.io/da       |                            |
|          | pr%202/2122/%20lectu       |                            |
|          | res/d%20apr%202\_%201      |                            |
|          | 3_diagnostics2.html)       |                            |
+----------+----------------------------+----------------------------+
| 10       | [Bootstrap                 | [Bootstrapping Regressi    |
|          | Theory](htt%20%            | on](ht%20tp                |
|          | 20ps%20:/%2%200/uoeps%20y. | s:%20%20/%20/u%20oeps%%202 |
|          | gi%20%20t%20hu%20b.io%%202 | 0y.githu%20%20%20%20b.%20i |
|          | 0/dapr2/%20%20%20%2021%202 | o/dapr%202/212%20%2%%20200 |
|          | 2/lect%20ures/%20%2%%20200 | 2/lab%20s/1%20_1%200%20%20 |
|          | dapr2%20_14%20_B%20o%20%20 | %%2020_bootstrap_reg.html) |
|          | %%2020otstrapTheory.html)\ |                            |
|          | [Bootstrap for Regre       |                            |
|          | ssion](ht%2%200tps://%20uo |                            |
|          | ep%20%20s%20y.%20gith%%202 |                            |
|          | 0ub.io/d%20%20%20%20ap%20r |                            |
|          | 2/2122%20/lect%20%2%%20200 |                            |
|          | ures/%20dap%20r2%20_%20%20 |                            |
|          | %%202014_BootstrapLM.html) |                            |
+----------+----------------------------+----------------------------+
| 11       | -- No Lecture --           | [Writing U                 |
|          |                            | p]                         |
|          |                            | (h%20%20t%20tp%20s://%%202 |
|          |                            | 0uoepsy.%20%20%20%20gi%20t |
|          |                            | hub.io%20/dapr%20%2%%20200 |
|          |                            | 2/212%202/l%20ab%20s%20%20 |
|          |                            | %%2020/1_11_write_up.html) |
+----------+----------------------------+----------------------------+

#### **Semester 2**

+----------+----------------------------+----------------------------+
| **Week** | **Lecture**                | **Workbook**               |
+:=========+:===========================+:===========================+
| 1        | [Model Co mp               | \[Model Comparison\] (h t  |
|          | arison](htt%20%            | tps://uo%20epsy.gith ub .  |
|          | 20ps%20:/%2%200/uoeps%20y. | io/dapr2/2122/%20lab s/ 2  |
|          | gi%20%20t%20hu%20b.io%%202 | \_01_model_comp.html)      |
|          | 0/dapr2/%20%20%20%2021%202 |                            |
|          | 2/lect%20ures/%20%2%%20200 |                            |
|          | dapr2%20_15%20_m%20o%20%20 |                            |
|          | %%2020del_comparison.html) |                            |
+----------+----------------------------+----------------------------+
| 2        | [Coding Categorical Predic | [Coding Categorical        |
|          | tors](htt%20ps://%20%      | Predictor                  |
|          | 20uo%20ep%2%200sy.git%20hu | s](htt%20ps                |
|          | b.%20%20i%20o/%20dapr%%202 | :/%20%20/%20uo%20epsy%%202 |
|          | 02/2122/%20%20%20%20le%20c | 0.github%20%20%20%20.i%20o |
|          | tures/%20dapr2%20%2%%20200 | /dapr2%20/2122%20%2%%20200 |
|          | _16_c%20odi%20ng%20c%20%20 | /labs%20/2_%2002%20_%20%20 |
|          | %%2020ategoricaldata.html) | %%2020coding_factors.html) |
+----------+----------------------------+----------------------------+
| 3        | [Experimental D es         | [Contrasts, Study Design & |
|          | igns](https%20%            | Factorial AN OV            |
|          | 20:/%20/u%2%200oepsy.%20gi | A                          |
|          | th%20%20u%20b.%20io/d%%202 | ](ht%20tp%2%200s://uo%20ep |
|          | 0apr2/21%20%20%20%2022%20/ | sy%20%20.%20gi%20thub%%202 |
|          | lectur%20es/da%20%2%%20200 | 0.io/dap%20%20%20%20r2%20/ |
|          | pr2_1%207_e%20xp%20e%20%20 | 2122/l%20abs/2%20%2%%20200 |
|          | %%2020rimentaldesign.html) | _03_c%20ont%20_d%20e%20%20 |
|          |                            | %%2020sign_factanova.html) |
+----------+----------------------------+----------------------------+
| 4        | [Factorial D               | [Two-Way ANOV              |
|          | esigns](htt%20%            | A](http%20s:               |
|          | 20ps%20:/%2%200/uoeps%20y. | //%20%20u%20oe%20psy.%%202 |
|          | gi%20%20t%20hu%20b.io%%202 | 0github.%20%20%20%20io%20/ |
|          | 0/dapr2/%20%20%20%2021%202 | dapr2/%202122/%20%2%%20200 |
|          | 2/lect%20ures/%20%2%%20200 | labs/%202_0%204_%20f%20%20 |
|          | dapr2%20_18%20_f%20a%20%20 | %%2020actorial_anova.html) |
|          | %%2020ctorialdesigns.html) |                            |
+----------+----------------------------+----------------------------+
| 5        | [Multiple Comparison &     | \[Assumptions, Multiple    |
|          | Assumpt                    | Comparisons, Corrections & |
|          | ions](htt%20ps://%20%      | Writing u p\]              |
|          | 20uo%20ep%2%200sy.git%20hu | (h%20ttps:/%20/uoe%20p     |
|          | b.%20%20i%20o/%20dapr%%202 | sy.git%%2020hub.io/%20     |
|          | 02/2122/%20%20%20%20le%20c | da%20pr2/212%202/lab%2     |
|          | tures/%20dapr2%20%2%%20200 | 0s/2_0%205_m%20ul%20t%     |
|          | _19_r%20evi%20si%20t%20%20 | 20i_comp_writeup.html)     |
|          | %%2020ingassumptions.html) |                            |
+----------+----------------------------+----------------------------+
| 6        | -- Break Week --           | --                         |
+----------+----------------------------+----------------------------+
| 7        | [Binary Logistic           | \[Logistic Regress ion\]   |
|          | Regression                 | (https:%%2020//uoeps       |
|          | I](htt%20%                 | y.%20github.%20io/da       |
|          | 20ps%20:/%2%200/uoeps%20y. | pr2/2%20122%20/l%20a       |
|          | gi%20%20t%20hu%20b.io%%202 | bs/2_07_binary.html)       |
|          | 0/dapr2/%20%20%20%2021%202 |                            |
|          | 2/lect%20ures/%20%2%%20200 |                            |
|          | dapr2%20_20%20_b%20i%20%20 |                            |
|          | %%2020narylogistic1.html)\ |                            |
|          | [Binary Logistic           |                            |
|          | Regression I               |                            |
|          | I](ht%20%                  |                            |
|          | 20tp%20s:%2%200//uoep%20sy |                            |
|          | .g%20%20i%20th%20ub.i%%202 |                            |
|          | 0o/dapr2%20%20%20%20/2%201 |                            |
|          | 22/lec%20tures%20%2%%20200 |                            |
|          | /dapr%202_2%200_%20b%20%20 |                            |
|          | %%2020inarylogistic2.html) |                            |
+----------+----------------------------+----------------------------+
| 8        | \[Intro to the Generalised | [More Logistic Regress     |
|          | Linear Model (G LM)\]      | ion](h%20tt                |
|          | (https:%20//uo%20%20e%20ps | ps%20%20:%20//%20uoep%%202 |
|          | y.gi%%2020thub.io%20%20%20 | 0sy.gith%20%20%20%20ub%20. |
|          | /d%20apr2/21%2022/le%20%2% | io/dap%20r2/21%20%2%%20200 |
|          | 200cture%20s/d%20ap%20r%20 | 22/la%20bs/%202_%200%20%20 |
|          | %%20202_21_introglm.html)\ | %%20208_morelogistic.html) |
|          | [Intro to Missing          |                            |
|          | Data](htt%20%              |                            |
|          | 20ps%20:/%2%200/uoeps%20y. |                            |
|          | gi%20%20t%20hu%20b.io%%202 |                            |
|          | 0/dapr2/%20%20%20%2021%202 |                            |
|          | 2/lect%20ures/%20%2%%20200 |                            |
|          | dapr2%20_20%20_i%20n%20%20 |                            |
|          | %%2020tromissingdata.html) |                            |
+----------+----------------------------+----------------------------+
| 9        | [Exploratory vs            | [Exploratory vs            |
|          | Confirmatory Analys        | Confirmatory A             |
|          | is](ht%20tps%20://uo%20%   | nalysis](ht                |
|          | 20ep%20sy%2%200.githu%20b. | tp%20%20s%20:/%20/uoe%%202 |
|          | io%20%20/%20da%20pr2/%%202 | 0psy.git%20%20%20%20hu%20b |
|          | 02122/le%20%20%20%20ct%20u | .io/da%20pr2/2%20%2%%20200 |
|          | res/Ex%20plora%20%2%%20200 | 122/l%20abs%20/2%20_%20%20 |
|          | tory_%20Con%20fi%20r%20%20 | %%202009_exp_vs_conf.html) |
|          | %%2020matory_Analysis.pdf) |                            |
+----------+----------------------------+----------------------------+
| 10       | \[Power for Linear Model   | \[Power for Linear Mo      |
|          | s\] (h%20ttps:/%20/uoe%20p | dels\]                     |
|          | sy.git%%2020hub.io/%20     | (https%%2020://uoep%20     |
|          | da%20pr2/212%202/lec%2     | sy%20.github%20.io/d%2     |
|          | 0tures%20/da%20pr%202%     | 0apr2/%20212%202/%20l%     |
|          | 20_22_intropower.html)     | 20abs/2_10_power.html)     |
+----------+----------------------------+----------------------------+
| 11       | [Reproducibility, Open     | [Recap]                    |
|          | Science & Preregi stra     | (https:/%20%20%20%20/u%20o |
|          | tio                        | epsy.g%20ithub%20%2%%20200 |
|          | n](ht%20tps://uo%20%20%20% | .io/d%20apr%202/%202%20%20 |
|          | 20e%20ps%20y.g%20ithub%20% | %%2020122/labs/2_11_recap) |
|          | 20.i%20o/%2%200dapr2/%2021 |                            |
|          | 22%20%20/%20le%20ctur%%202 |                            |
|          | 0es/Repr%20%20%20%20od%20u |                            |
|          | cibili%20ty_Op%20%2%%20200 |                            |
|          | en_Sc%20ien%20ce%20_%20%20 |                            |
|          | %%2020Preregistration.pdf) |                            |
+----------+----------------------------+----------------------------+

| Week |               Lecture                |       Practical        |
|:----:|:------------------------------------:|:----------------------:|
| Pre  |  Preparing to become a Psychologist  |                        |
|  WW  |       Let's measure some stuff       |                        |
|  1   |    Answering questions with data     | Doing stuff with stuff |
|  2   |  Finding patterns and relationships  |                        |
|  3   |       Correlations and models        |                        |
|  4   |      Distributions and sampling      |                        |
|  5   |      Probabilities and P-Values      |                        |
|  RW  |                 \--                  |          \--           |
|  6   | Open Science, Reporting and Critique |                        |
|  7   |         Qualitative Research         |                        |
|  8   |        Correlational Research        |                        |
|  9   |    Q u asi-Experimental Research     |                        |
|  10  |        Experimental Research         |                        |

: Y2 Term 1 Laydown

| Term 2 |                               |     |
|:------:|:-----------------------------:|:---:|
|   1    |      Statistical Models       |     |
|   2    |    Inferential Statistics     |     |
|   3    |    Power and Effect Sizes     |     |
|   4    |          Correlation          |     |
|   5    |          Regression           |     |
|   RW   |              \--              | \-- |
|   6    |      Multiple Regression      |     |
|   7    |      Logistic Regression      |     |
|   8    |      Comparing two means      |     |
|   9    |    Comparing several means    |     |
|   10   | Data Skills for Employability |     |

Y2 Term 2 Laydown

\newpage

\newpage

## Level 7 - topline summary

| Week |              Lecture               |       Practical        |
|:----:|:----------------------------------:|:----------------------:|
| Pre  | Preparing to become a Psychologist |                        |
|  WW  |      Let's measure some stuff      |                        |
|  1   |   Answering questions with data    | Doing stuff with stuff |
|  2   | Finding patterns and relationships |                        |
|  3   |      Correlations and models       |                        |
|  4   |     Distributions and sampling     |                        |
|  5   |     Probabilities and P-Values     |                        |
|  RW  |                \--                 |          \--           |

\newpage

1.  \
