---
title: Dissertation (Y3)
---

## Level 6 - topline summary

### Module Content

5 week module to jumpstart the dissertation and to actively help find
supervision.

Obviously, this could be useful in terms of saving repetition for
supervisors, and for bringing consistency.

Could be useful to MSc students. They could access the entire Goldsmiths
Research Skills archive and have that as a foundation to the research
side of things/refresher for RM.

Great for Conversion students and PANC/non-BPS/Psych

Get people up and running earlier - starts in summer/WW.

Off the shelf projects? Individual? Qual? Quant?

### Module Learning Outcomes

### Assessment

| Assessment Element | Length | \%  | F or S | LO Tested |
|--------------------|--------|-----|--------|-----------|
|                    |        |     |        |           |
|                    |        |     |        |           |
|                    |        |     |        |           |

### Reading and Resource List

We have a custom made textbook to support key study skills throughout
your degree:

\newpage

| Week | Lecture | Practical |
|:----:|:-------:|:---------:|
| Pre  |         |    \--    |
|  WW  |   \--   |  \-\-\--  |
|  1   |   \--   |    \--    |
|  2   |   \--   |    \--    |
|  3   |   \--   |    \--    |
|  4   |   \--   |    \--    |
|  5   |   \--   |    \--    |
|  RW  |         |    \--    |

: Y3 Term 1 Laydown
