---
title: QAA
---

# QAA Benchmarks

3.4 Research methods are integral to psychology and students obtain a
sound knowledge of, and a proven ability to use, a range of both
qualitative and quantitative methods appropriately. Knowledge and
understanding of how to obtain and analyse evidence is best acquired and
demonstrated through extensive and progressive empirical work in
laboratory and naturalistic settings through all stages of a degree.

3.5 Psychology students learn the basic principles of sound data
collection. Given the broad theoretical scope of psychology, rigorous
specialist training is required to engender a critical understanding of
the role of experimental design, the choice of research methods
employed, and the analytic approach taken, for testing psychological
theories.

Subject knowledge and understanding 6.3 On graduating with an honours
degree in psychology, graduates are able to:

1.  understand the scientific underpinnings of psychology as a
    discipline, its historical origins, development and limitations

2.  recognise the inherent variability and diversity of psychological
    functioning and its significance

3.  demonstrate systematic knowledge and critical understanding of a
    range of influences on psychological functioning, how they are
    conceptualised across the core areas as outlined in paragraphs 4.4
    and 4.5 and how they interrelate

4.  demonstrate detailed knowledge of several specialised areas and/or
    applications, some of which are at the cutting edge of research in
    the discipline

5.  demonstrate a systematic knowledge of a range of research paradigms,
    research methods and measurement techniques, including statistics
    and probability, and be aware of their limitations.

Subject-specific skills 6.4 On graduating with an honours degree in
psychology, graduates are able to:

1.  reason scientifically, understand the role of evidence and make
    critical judgements about arguments in psychology

2.  adopt multiple perspectives and systematically analyse the
    relationships between them

3.  detect meaningful patterns in behaviour and evaluate their
    significance

4.  recognise the subjective and variable nature of individual
    experience

5.  pose, operationalise and critique research questions

6.  demonstrate substantial competence in research skills through
    practical activities

7.  reason analytically and demonstrate competence in a range of
    quantitative and qualitative methods

8.  competently initiate, design, conduct and report on an
    empirically-based research project under appropriate supervision,
    and recognise its theoretical, practical and methodological
    implications and limitations

9.  be aware of ethical principles and approval procedures and
    demonstrate these in relation to personal study, particularly with
    regard to the research project, and be aware of the ethical context
    of psychology as a discipline.

Generic skills 6.5 On graduating with an honours degree in psychology,
graduates are able to:

1.  **communicate ideas and research findings by written, oral and
    visual means**

2.  **interpret and use numerical, textual and other forms of data**

3.  **be computer literate, for the purposes of furthering their own
    learning and in the analysis and presentation of ideas and research
    findings**

4.  **solve problems by clarifying questions, considering alternative
    solutions and evaluating outcomes**

5.  **be sensitive to, and take account of, contextual and interpersonal
    factors in groups and teams**

6.  **undertake self-directed study and project management, in order to
    meet desired objectives**

7.  **take charge of their own learning, and reflect and evaluate
    personal strengths and weaknesses for the purposes of future
    learning.**
