---
title: Foundation Year schedule
df-print: kable
format: 
  pdf: default
  html: default
---

|   Week   | Schedule     |                                                                |              |                                                                |
|:-----------:|:------------|:---------------|:------------|:------------------|
|  **1**   | **Lecture:** | There was a wee cooper who lived in fife and his hat was green | **IndStud:** | There was a wee cooper who lived in fife and his hat was green |
|          | **Lab:**     | There was a wee cooper who lived in fife and his hat was green | **Data:**    | There was a wee cooper who lived in fife and his hat was green |
|  **2**   | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
|  **3**   | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
|  **4**   | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
|  **5**   | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
|          |              | Reading Week                                                   |              |                                                                |
|  **6**   | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
|  **7**   | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
|  **8**   | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
|  **9**   | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
|  **10**  | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
\newpage

|   Week   | Schedule     |                                                                |              |                                                                |
|:-----------:|:------------|:---------------|:------------|:------------------|
|  **11**   | **Lecture:** | There was a wee cooper who lived in fife and his hat was green | **IndStud:** | There was a wee cooper who lived in fife and his hat was green |
|          | **Lab:**     | There was a wee cooper who lived in fife and his hat was green | **Data:**    | There was a wee cooper who lived in fife and his hat was green |
|  **12**   | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
|  **13**  | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
|  **14**  | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
|  **15**  | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
|          |              | **Reading Week**                                               |              |                                                                |
|  **16**  | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
|  **17**  | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
|  **18**  | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
|  **19**  | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |
|  **20**  | **Lecture:** |                                                                | **IndStud:** |                                                                |
|          | **Lab:**     |                                                                | **Data:**    |                                                                |