---
title: Year 1 schedule
df-print: kable
---

Year 1 Term 1

+----+----------+-------------------+---------+-----------------------+
| We | Schedule |                   |         |                       |
| ek |          |                   |         |                       |
+:==:+:=========+:==================+:========+:======================+
| 0  | Wel      | Data Frenzy on    |         |                       |
|    | comeWeek | wellbeing?        |         |                       |
+----+----------+-------------------+---------+-----------------------+
| *  | **Le     | The year ahead    | *       | Intro to Posit Cloud  |
| *1 | cture:** | and answering     | *DataSk | & R and develop a     |
| ** |          | questions with    | ills:** | group question        |
|    |          | data              |         |                       |
+----+----------+-------------------+---------+-----------------------+
|    | **Lab:** | Visualisation and |         |                       |
|    |          | descriptives      |         |                       |
|    |          | (Team Coding)     |         |                       |
+----+----------+-------------------+---------+-----------------------+
| ** | **Le     | What is Science?  | *       | Descriptive Stats and |
| 2a | cture:** | Is Psychology a   | *DataSk | the Psych package     |
| ** |          | Science?          | ills:** |                       |
|    |          |                   |         |                       |
|    |          | Patterns and      |         |                       |
|    |          | relationships     |         |                       |
+----+----------+-------------------+---------+-----------------------+
|    | **Lab:** | Process your      |         |                       |
|    |          | group question    |         |                       |
|    |          | and submit poster |         |                       |
+----+----------+-------------------+---------+-----------------------+
| ** | **Le     | Open Science and  | *       | APA referencing and   |
| 3a | cture:** | the Replication   | *DataSk | Lit Searching &       |
| ** |          | Crisis            | ills:** | Zotero                |
|    |          |                   |         |                       |
|    |          | Critical Thinking |         |                       |
|    |          | and being         |         |                       |
|    |          | Scientific        |         |                       |
+----+----------+-------------------+---------+-----------------------+
|    | **Lab:** | Block A           |         |                       |
|    |          | Experiment        |         |                       |
+----+----------+-------------------+---------+-----------------------+
| ** | **Le     | Critical Thinking | *       | Critical Analysis &   |
| 4a | cture:** | and Thinking      | *DataSk | Research Summary      |
| ** |          | Scientifically    | ills:** | exercise              |
+----+----------+-------------------+---------+-----------------------+
|    | **Lab:** | Literature review |         |                       |
|    |          | & Critical        |         |                       |
|    |          | Analysis          |         |                       |
+----+----------+-------------------+---------+-----------------------+
| ** | **Le     | The research      | *       | Compare two papers    |
| 5b | cture:** | toolkit - Qual &  | *DataSk | Q&Q                   |
| ** |          | Quant -           | ills:** |                       |
+----+----------+-------------------+---------+-----------------------+
|    | **Lab:** | Reporting         |         |                       |
|    |          | Research          |         |                       |
+----+----------+-------------------+---------+-----------------------+
| ** |          | Field Trip        |         |                       |
| RW |          |                   |         |                       |
| ** |          |                   |         |                       |
+----+----------+-------------------+---------+-----------------------+
| ** | **Le     | Observational     | *       | Lab Report Structure  |
| 6b | cture:** | Research          | *DataSk |                       |
| ** |          |                   | ills:** |                       |
+----+----------+-------------------+---------+-----------------------+
|    | **Lab:** | Block B           |         |                       |
|    |          | Experiment        |         |                       |
+----+----------+-------------------+---------+-----------------------+
| ** | **Le     | Ethnography &     | *       | \--                   |
| 7b | cture:** | Case Study        | *DataSk |                       |
| ** |          |                   | ills:** |                       |
+----+----------+-------------------+---------+-----------------------+
|    | **Lab:** | \--               | *       | Lab Report 1 - Q or Q |
|    |          |                   | *Assign |                       |
|    |          |                   | ment:** |                       |
+----+----------+-------------------+---------+-----------------------+
| ** | **Le     | Sampling &        | *       | \--                   |
| 8c | cture:** | Probability       | *DataSk |                       |
| ** |          |                   | ills:** |                       |
+----+----------+-------------------+---------+-----------------------+
|    | **Lab:** | \--               |         |                       |
+----+----------+-------------------+---------+-----------------------+
| ** | **Le     | Statistical       | *       | \--                   |
| 9c | cture:** | Models            | *DataSk |                       |
| ** |          |                   | ills:** |                       |
+----+----------+-------------------+---------+-----------------------+
|    | **Lab:** | Block C           | *       | Bibliography: Peer &  |
|    |          | Experiment        | *Assign | Formative assessment  |
|    |          |                   | ment:** |                       |
+----+----------+-------------------+---------+-----------------------+
| *  | **Le     | Correlational     | *       | Blog or Vlog          |
| *1 | cture:** | Research          | *DataSk |                       |
| 0c |          |                   | ills:** |                       |
| ** |          |                   |         |                       |
+----+----------+-------------------+---------+-----------------------+
|    | **Lab:** | Bibliography      | *       | Summary Blog/Vlog     |
|    |          | Presentations     | *Assign |                       |
|    |          |                   | ment:** |                       |
+----+----------+-------------------+---------+-----------------------+

\newpage

Year 1 Term 2

+----+---------+--------------------+---------+-----------------+
| We | S       |                    |         |                 |
| ek | chedule |                    |         |                 |
+:==:+=========+====================+=========+=================+
| ** | **Lec   | Employability      | *       | Employability   |
| 11 | ture:** |                    | *DataSk |                 |
| ** |         |                    | ills:** |                 |
+----+---------+--------------------+---------+-----------------+
|    | *       | Careers / Pathways |         |                 |
|    | *Lab:** |                    |         |                 |
+----+---------+--------------------+---------+-----------------+
| *  | **Lec   | Qual data          | *       | Transcript      |
| *1 | ture:** | collection         | *DataSk | coding          |
| 2a |         |                    | ills:** |                 |
| ** |         |                    |         |                 |
+----+---------+--------------------+---------+-----------------+
|    | *       | Interviewing       |         |                 |
|    | *Lab:** | skills             |         |                 |
+----+---------+--------------------+---------+-----------------+
| *  | **Lec   | Qual analysis &    | *       | Coding swap     |
| *1 | ture:** | writeup            | *DataSk |                 |
| 3a |         |                    | ills:** |                 |
| ** |         |                    |         |                 |
+----+---------+--------------------+---------+-----------------+
|    | *       | Block A Experiment |         |                 |
|    | *Lab:** |                    |         |                 |
+----+---------+--------------------+---------+-----------------+
| *  | **Lec   | Mixing methods     | *       | \--             |
| *1 | ture:** |                    | *DataSk |                 |
| 4a |         |                    | ills:** |                 |
| ** |         |                    |         |                 |
+----+---------+--------------------+---------+-----------------+
|    | *       | \--                | *       | Lab Report 2    |
|    | *Lab:** |                    | *Assign | QorQ            |
|    |         |                    | ment:** |                 |
+----+---------+--------------------+---------+-----------------+
| *  | **Lec   | Multiple           | *       | \--             |
| *1 | ture:** | Regression         | *DataSk |                 |
| 5b |         |                    | ills:** |                 |
| ** |         |                    |         |                 |
+----+---------+--------------------+---------+-----------------+
|    | *       | \--                |         |                 |
|    | *Lab:** |                    |         |                 |
+----+---------+--------------------+---------+-----------------+
| ** |         |                    |         |                 |
| RW |         |                    |         |                 |
| ** |         |                    |         |                 |
+----+---------+--------------------+---------+-----------------+
| *  | **Lec   | Experimental       | *       | \--             |
| *1 | ture:** | Designs            | *DataSk |                 |
| 6b |         |                    | ills:** |                 |
| ** |         |                    |         |                 |
+----+---------+--------------------+---------+-----------------+
|    | *       | Block B Experiment |         |                 |
|    | *Lab:** |                    |         |                 |
+----+---------+--------------------+---------+-----------------+
| *  | **Lec   | Comparing Means    | *       | \--             |
| *1 | ture:** | (1,2)              | *DataSk |                 |
| 7b |         |                    | ills:** |                 |
| ** |         |                    |         |                 |
+----+---------+--------------------+---------+-----------------+
|    | *       | \--                | *       | Lab Report 3    |
|    | *Lab:** |                    | *Assign | QorQ            |
|    |         |                    | ment:** |                 |
+----+---------+--------------------+---------+-----------------+
| *  | **Lec   | One way ANOVA      | *       | \--             |
| *1 | ture:** |                    | *DataSk |                 |
| 8c |         |                    | ills:** |                 |
| ** |         |                    |         |                 |
+----+---------+--------------------+---------+-----------------+
|    | *       | \--                |         |                 |
|    | *Lab:** |                    |         |                 |
+----+---------+--------------------+---------+-----------------+
| *  | **Lec   | Two way ANOVA      | *       | \--             |
| *1 | ture:** |                    | *DataSk |                 |
| 9c |         |                    | ills:** |                 |
| ** |         |                    |         |                 |
+----+---------+--------------------+---------+-----------------+
|    | *       | Block C Experiment |         |                 |
|    | *Lab:** |                    |         |                 |
+----+---------+--------------------+---------+-----------------+
| *  | **Lec   | Non-Parametrics    | *       | \--             |
| *2 | ture:** |                    | *DataSk |                 |
| 0c |         |                    | ills:** |                 |
| ** |         |                    |         |                 |
+----+---------+--------------------+---------+-----------------+
|    | *       | \--                | *       | Bibliography    |
|    | *Lab:** |                    | *Assign | final           |
|    |         |                    | ment:** | submission      |
+----+---------+--------------------+---------+-----------------+
